camunda:
  base-url: ${CAMUNDA_BASE_URL:http://localhost:8080/engine-rest}
  username: ${CAMUNDA_USERNAME:}
  password: ${CAMUNDA_PASSWORD:}

logging:
  level:
    sa.gov.saip: INFO
    sa.gov.saip.workflow.camunda: WARN
springdoc:
  api-docs:
    enabled: false
