spring:
  application:
    name: copy-right-service
  profiles:
    active: local

server:
  port: 8081

workflow:
  engine: camunda

camunda:
  enabled: true
  base-url: http://localhost:8080/engine-rest
  username:
  password:
  connect-timeout: 5s
  read-timeout: 30s
  auto-deployment:
    enabled: true
    resource-pattern: classpath*:processes/**/*.bpmn
    deployment-name-prefix: auto

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  show-actuator: true
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

logging:
  pattern:
    level: "%5p [correlationId:%X{correlationId:-}]"
  level:
    sa.gov.saip: INFO
    sa.gov.saip.workflow.camunda: INFO
    org.springframework.web: INFO
